<?php

namespace App\PlatformAPI\Mindbody\Traits;

trait SetFakeMindbodyData
{
    protected function setLocations()
    {
        $this->locations = collect([
            [
                "AdditionalImageURLs" => [],
                "Address" => "64 West Kimberly Court",
                "Address2" => "Bozeman MT 59718",
                "Amenities" => [],
                "BusinessDescription" => null,
                "City" => "Bozeman",
                "Description" => null,
                "HasClasses" => true,
                "Id" => 1,
                "Latitude" => 0.0,
                "Longitude" => 0.0,
                "Name" => "Demo Quicker Notes",
                "Phone" => "14065392356",
                "PhoneExtension" => "223",
                "PostalCode" => "59718",
                "SiteID" => -99787,
                "StateProvCode" => "MT",
                "Tax1" => 0.0,
                "Tax2" => 0.0,
                "Tax3" => 0.0,
                "Tax4" => 0.0,
                "Tax5" => 0.0,
                "TotalNumberOfRatings" => 0,
                "AverageRating" => 0.0,
                "TotalNumberOfDeals" => 0,
            ],
            [
                "AdditionalImageURLs" => [],
                "Address" => null,
                "Address2" => null,
                "Amenities" => [],
                "BusinessDescription" => null,
                "City" => null,
                "Description" => null,
                "HasClasses" => false,
                "Id" => 2,
                "Latitude" => null,
                "Longitude" => null,
                "Name" => "QuickerNotes Sandbox Site 2",
                "Phone" => null,
                "PhoneExtension" => null,
                "PostalCode" => null,
                "SiteID" => -99787,
                "StateProvCode" => null,
                "Tax1" => 0.0,
                "Tax2" => 0.0,
                "Tax3" => 0.0,
                "Tax4" => 0.0,
                "Tax5" => 0.0,
                "TotalNumberOfRatings" => 0,
                "AverageRating" => 0.0,
                "TotalNumberOfDeals" => 0,
            ],
            [
                "AdditionalImageURLs" => [],
                "Address" => "234 East Main Street",
                "Address2" => "Bozeman MT 59715",
                "Amenities" => [],
                "BusinessDescription" => null,
                "City" => "Bozeman",
                "Description" => null,
                "HasClasses" => false,
                "Id" => 2,
                "Latitude" => 45.6791405,
                "Longitude" => -111.0331703,
                "Name" => "QuickerNotes Sandbox Site 2",
                "Phone" => "4444444444",
                "PhoneExtension" => null,
                "PostalCode" => "59715",
                "SiteID" => 16134,
                "StateProvCode" => "MT",
                "Tax1" => 0.0,
                "Tax2" => 0.0,
                "Tax3" => 0.0,
                "Tax4" => 0.0,
                "Tax5" => 0.0,
                "TotalNumberOfRatings" => 0,
                "AverageRating" => 0.0,
                "TotalNumberOfDeals" => 0,
            ],
            [
                "AdditionalImageURLs" => [],
                "Address" => "123 East Main Street",
                "Address2" => "Bozeman MT 59715",
                "Amenities" => [],
                "BusinessDescription" => null,
                "City" => "Bozeman",
                "Description" => null,
                "HasClasses" => false,
                "Id" => 1,
                "Latitude" => 45.6793256,
                "Longitude" => -111.0348995,
                "Name" => "QuickerNotes Sandbox Site 3",
                "Phone" => "4444444444",
                "PhoneExtension" => null,
                "PostalCode" => "59715",
                "SiteID" => 16134,
                "StateProvCode" => "MT",
                "Tax1" => 0.0,
                "Tax2" => 0.0,
                "Tax3" => 0.0,
                "Tax4" => 0.0,
                "Tax5" => 0.0,
                "TotalNumberOfRatings" => 0,
                "AverageRating" => 0.0,
                "TotalNumberOfDeals" => 0,
            ],
        ]);
    }

    protected function setStaff()
    {
        $this->staff = collect([
            [
                "siteId" => -99787,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => null,
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "Autoemail",
                "HomePhone" => null,
                "Id" => -5,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "Autoemail",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => null,
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => -99787,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => null,
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "Client",
                "HomePhone" => null,
                "Id" => -4,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "Client",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => null,
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => -99787,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => null,
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "STAFF",
                "HomePhone" => null,
                "Id" => 1,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "STAFF",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => null,
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => -99787,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => "",
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "Dr. Quinn",
                "HomePhone" => null,
                "Id" => 2,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "Medicine Woman",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => "https://clients.mindbodyonline.com/studios/DemoQuickerNotesDustinF/staff/2_large.jpg?imageversion=1571980054",
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => -99787,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => "",
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "Dr. Foo",
                "HomePhone" => null,
                "Id" => 100000002,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "Bar",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => "https://clients.mindbodyonline.com/studios/DemoQuickerNotesDustinF/staff/2_large.jpg?imageversion=1571980054",
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => 16134,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => null,
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "Autoemail",
                "HomePhone" => null,
                "Id" => -5,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "Autoemail",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => null,
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => 16134,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => "",
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "Hassan",
                "HomePhone" => null,
                "Id" => 100000001,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "Jamal",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => null,
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => 16134,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => null,
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "Client",
                "HomePhone" => null,
                "Id" => -4,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "Client",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => null,
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
            [
                "siteId" => 16134,
                "Address" => null,
                "AppointmentInstructor" => false,
                "AlwaysAllowDoubleBooking" => false,
                "Bio" => null,
                "City" => null,
                "Country" => null,
                "Email" => null,
                "FirstName" => "STAFF",
                "HomePhone" => null,
                "Id" => 1,
                "IndependentContractor" => false,
                "IsMale" => false,
                "LastName" => "STAFF",
                "MobilePhone" => null,
                "Name" => null,
                "PostalCode" => null,
                "ClassTeacher" => false,
                "SortOrder" => 0,
                "State" => null,
                "WorkPhone" => null,
                "ImageUrl" => null,
                "Appointments" => [],
                "Unavailabilities" => [],
                "Availabilities" => [],
            ],
        ]);
    }

    protected function setClient()
    {
        $this->clients = collect([
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2019-01-22T00:00:00",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => null,
                "FirstName" => "Acme Inc",
                "Id" => "100000027",
                "IsCompany" => true,
                "IsProspect" => false,
                "LastName" => "Acme Inc",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "MT",
                "UniqueId" => 100000027,
                "LastModifiedDateTime" => "2019-01-23T00:53:21.7Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => "M",
                "ProspectStage" => null,
                "Email" => "acme@example.com",
                "MobilePhone" => null,
                "HomePhone" => "4065392356",
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => "64 W Kimberly Ct",
                "AddressLine2" => null,
                "City" => "Bozeman",
                "PostalCode" => "59718-9182",
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "None",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],[
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2019-01-22T00:00:00",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => null,
                "FirstName" => "Acme Inc",
                "Id" => "100000027",
                "IsCompany" => true,
                "IsProspect" => false,
                "LastName" => "Acme Inc",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "MT",
                "UniqueId" => 100000027,
                "LastModifiedDateTime" => "2019-01-23T00:53:21.7Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => "M",
                "ProspectStage" => null,
                "Email" => "acme@example.com",
                "MobilePhone" => null,
                "HomePhone" => "4065392356",
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => "64 W Kimberly Ct",
                "AddressLine2" => null,
                "City" => "Bozeman",
                "PostalCode" => "59718-9182",
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "None",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => 16134,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2017-11-21T13:27:43.99",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2017-11-20T00:00:00",
                "FirstName" => "Jessica",
                "Id" => "100000020",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Alba",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "CA",
                "UniqueId" => 100000020,
                "LastModifiedDateTime" => "2017-11-22T08:29:38.9Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Female",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2019-09-16T11:59:36.967",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2019-09-16T00:00:00",
                "FirstName" => "Jamal",
                "Id" => "jamal_new",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Another Client",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "CA",
                "UniqueId" => 100000029,
                "LastModifiedDateTime" => "2019-09-17T07:31:32.2Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => "hassanjamal@live.com",
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => "1986-03-13T00:00:00",
                "Country" => "US",
                "CreationDate" => "2015-05-12T08:47:03.753",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [
                    0 => [
                        "Id" => 2,
                        "ValueId" => 8,
                    ],
                ],
                "ClientRelationships" => [
                    0 => [
                        "RelatedClientId" => "new",
                        "Relationship" => [
                            "Id" => -1,
                            "RelationshipName1" => "Referred",
                            "RelationshipName2" => "Referred By",
                        ],
                        "RelationshipName" => "Referred",
                        "Delete" => false,
                    ],
                    1 => [
                        "RelatedClientId" => "100000001",
                        "Relationship" => [
                            "Id" => -1,
                            "RelationshipName1" => "Referred",
                            "RelationshipName2" => "Referred By",
                        ],
                        "RelationshipName" => "Referred By",
                        "Delete" => false,
                    ],
                ],
                "FirstAppointmentDate" => "2015-05-12T00:00:00",
                "FirstName" => "Jessica",
                "Id" => "100000003",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Biel",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "CA",
                "UniqueId" => 100000003,
                "LastModifiedDateTime" => "2019-10-28T16:37:52.9Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => "Another client",
                "PhotoUrl" => "https://clients.mindbodyonline.com/studios/DEMOQUICKERNOTESDUSTINF/clients/100000003_large.jpg?imageversion=8",
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Female",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2017-11-21T13:16:51.687",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2017-11-20T00:00:00",
                "FirstName" => "Jim",
                "Id" => "100000019",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Carrey",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "CA",
                "UniqueId" => 100000019,
                "LastModifiedDateTime" => "2017-11-22T08:29:38.9Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => "https://clients.mindbodyonline.com/studios/DEMOQUICKERNOTESDUSTINF/clients/100000019_large.jpg?imageversion=8",
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => false,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => false,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => false,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => "2010-10-06T00:00:00",
                "Country" => "US",
                "CreationDate" => "2018-10-16T00:00:00",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2018-10-16T00:00:00",
                "FirstName" => "New",
                "Id" => "100000025",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Client",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "MT",
                "UniqueId" => 100000025,
                "LastModifiedDateTime" => "2018-10-17T07:15:19.4Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => "drfraker@gmail.com",
                "MobilePhone" => "14065392356",
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => "https://clients.mindbodyonline.com/studios/DEMOQUICKERNOTESDUSTINF/clients/100000025_large.jpg?imageversion=8",
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => "1996-10-03T00:00:00",
                "Country" => "US",
                "CreationDate" => "2018-10-17T08:29:26.707",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2018-10-17T00:00:00",
                "FirstName" => "Jane",
                "Id" => "100000026",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Doe",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "MT",
                "UniqueId" => 100000026,
                "LastModifiedDateTime" => "2019-10-17T16:41:09.5Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => "drfraker@gmail.com",
                "MobilePhone" => "14065392356",
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => "https://clients.mindbodyonline.com/studios/DEMOQUICKERNOTESDUSTINF/clients/100000026_large.jpg?imageversion=8",
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Female",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2018-07-24T12:14:59.877",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2018-07-24T00:00:00",
                "FirstName" => "Demo",
                "Id" => "100000024",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Dude",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "CA",
                "UniqueId" => 100000024,
                "LastModifiedDateTime" => "2018-07-25T07:21:07.4Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => "1982-09-28T00:00:00",
                "Country" => "US",
                "CreationDate" => "2019-09-09T00:00:00",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2019-09-09T00:00:00",
                "FirstName" => "Hassan",
                "Id" => "hassan_1",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "First Client",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "NY",
                "UniqueId" => 100000028,
                "LastModifiedDateTime" => "2019-09-10T07:44:52.3Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => "hs.jamal+qn1@gmail.com",
                "MobilePhone" => "2127852000",
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => "4, 150 Greenwich St 47 Floor,",
                "AddressLine2" => null,
                "City" => "NEW YORK",
                "PostalCode" => "10007",
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2017-11-21T13:28:34.193",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2017-11-21T00:00:00",
                "FirstName" => "John",
                "Id" => "100000021",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Goodman",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "CA",
                "UniqueId" => 100000021,
                "LastModifiedDateTime" => "2017-11-22T08:29:38.9Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2017-11-29T09:33:47.36",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2017-11-29T00:00:00",
                "FirstName" => "Jimmy",
                "Id" => "100000022",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Joe",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "CA",
                "UniqueId" => 100000022,
                "LastModifiedDateTime" => "2017-11-30T10:26:01.1Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "None",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => "1969-02-02T00:00:00",
                "Country" => "US",
                "CreationDate" => "2015-05-12T08:46:27.38",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [
                    0 => [
                        "Id" => 1,
                        "ValueId" => 2,
                    ],
                    1 => [
                        "Id" => 2,
                        "ValueId" => 8,
                    ],
                    2 => [
                        "Id" => 3,
                        "ValueId" => 10,
                    ],
                    3 => [
                        "Id" => 5,
                        "ValueId" => 11,
                    ],
                    4 => [
                        "Id" => 6,
                        "ValueId" => 12,
                    ],
                ],
                "ClientRelationships" => [
                    0 => [
                        "RelatedClientId" => "100000003",
                        "Relationship" => [
                            "Id" => -1,
                            "RelationshipName1" => "Referred",
                            "RelationshipName2" => "Referred By",
                        ],
                        "RelationshipName" => "Referred By",
                        "Delete" => false,
                    ],
                ],
                "FirstAppointmentDate" => "2015-05-12T00:00:00",
                "FirstName" => "Angelina",
                "Id" => "new",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Jolie",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => "client profile notes",
                "State" => "CA",
                "UniqueId" => 100000000,
                "LastModifiedDateTime" => "2019-10-14T09:56:24.5Z",
                "RedAlert" => "staff alert",
                "YellowAlert" => "yellow alert",
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => "drfraker@gmail.com",
                "MobilePhone" => null,
                "HomePhone" => "4065392356",
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => "64 West Kimberly Court",
                "AddressLine2" => null,
                "City" => "Bozeman",
                "PostalCode" => "59718",
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => "https://clients.mindbodyonline.com/studios/DEMOQUICKERNOTESDUSTINF/clients/100000000_large.jpg?imageversion=8",
                "EmergencyContactInfoName" => "Natasha Fraker",
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Female",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Active",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2019-09-16T12:50:15.4",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2019-09-16T00:00:00",
                "FirstName" => "Shahrukh",
                "Id" => "shah_9999",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Khan",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "CA",
                "UniqueId" => 100000030,
                "LastModifiedDateTime" => "2019-09-17T14:10:53Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => "shah@gmail.com",
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => "Some Address",
                "AddressLine2" => null,
                "City" => "Nw York",
                "PostalCode" => "11029",
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => "1974-01-02T00:00:00",
                "Country" => "US",
                "CreationDate" => "2015-05-12T08:46:37.41",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [
                    0 => [
                        "Id" => 1,
                        "ValueId" => 3,
                    ],
                    1 => [
                        "Id" => 2,
                        "ValueId" => 8,
                    ],
                ],
                "ClientRelationships" => [
                    0 => [
                        "RelatedClientId" => "100000003",
                        "Relationship" => [
                            "Id" => -1,
                            "RelationshipName1" => "Referred",
                            "RelationshipName2" => "Referred By",
                        ],
                        "RelationshipName" => "Referred",
                        "Delete" => false,
                    ],
                ],
                "FirstAppointmentDate" => "2015-05-12T00:00:00",
                "FirstName" => "Brad",
                "Id" => "100000001",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Pitt",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "CA",
                "UniqueId" => 100000001,
                "LastModifiedDateTime" => "2019-11-07T17:51:52Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => "drfraker@gmail.com",
                "MobilePhone" => null,
                "HomePhone" => "4065392356",
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => "64 West Kimberly Court",
                "AddressLine2" => null,
                "City" => "Bozeman",
                "PostalCode" => "59718",
                "WorkExtension" => null,
                "ReferredBy" => "Another Client",
                "PhotoUrl" => "https://clients.mindbodyonline.com/studios/DEMOQUICKERNOTESDUSTINF/clients/100000001_large.jpg?imageversion=8",
                "EmergencyContactInfoName" => "Natasha Fraker",
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Active",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2017-01-28T01:27:41.04",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2017-01-28T00:00:00",
                "FirstName" => "Bar",
                "Id" => "100000011",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Smith",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "CA",
                "UniqueId" => 100000011,
                "LastModifiedDateTime" => "2019-05-04T16:01:46.8Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "None",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => false,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => false,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => false,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => null,
                "Country" => "US",
                "CreationDate" => "2018-02-13T00:00:00",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => null,
                "FirstName" => "Jerry",
                "Id" => "100000023",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Tester",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => null,
                "Notes" => null,
                "State" => "MT",
                "UniqueId" => 100000023,
                "LastModifiedDateTime" => "2018-02-13T18:39:09.9Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => "999 Bogus Blvd.",
                "AddressLine2" => null,
                "City" => "BOZEMAN",
                "PostalCode" => "59718",
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => null,
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "None",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],
            [
                "AppointmentGenderPreference" => "None",
                "BirthDate" => "2006-12-06T00:00:00",
                "Country" => "US",
                "CreationDate" => "2015-05-12T08:47:15.263",
                "CustomClientFields" => [],
                "ClientCreditCard" => null,
                "ClientIndexes" => [
                    0 => [
                        "Id" => 2,
                        "ValueId" => 9,
                    ],
                ],
                "ClientRelationships" => [],
                "FirstAppointmentDate" => "2015-05-15T00:00:00",
                "FirstName" => "Justin",
                "Id" => "100000004",
                "IsCompany" => false,
                "IsProspect" => false,
                "LastName" => "Timberlake",
                "Liability" => [
                    "AgreementDate" => null,
                    "IsReleased" => false,
                    "ReleasedBy" => null,
                ],
                "LiabilityRelease" => false,
                "MembershipIcon" => 0,
                "MobileProvider" => 0,
                "Notes" => " ",
                "State" => "CA",
                "UniqueId" => 100000004,
                "LastModifiedDateTime" => "2019-07-08T17:15:00.5Z",
                "RedAlert" => null,
                "YellowAlert" => null,
                "MiddleName" => null,
                "ProspectStage" => null,
                "Email" => null,
                "MobilePhone" => null,
                "HomePhone" => null,
                "WorkPhone" => null,
                "AccountBalance" => 0.0,
                "AddressLine1" => null,
                "AddressLine2" => null,
                "City" => null,
                "PostalCode" => null,
                "WorkExtension" => null,
                "ReferredBy" => null,
                "PhotoUrl" => "https://clients.mindbodyonline.com/studios/DEMOQUICKERNOTESDUSTINF/clients/100000004_large.jpg?imageversion=8",
                "EmergencyContactInfoName" => null,
                "EmergencyContactInfoEmail" => null,
                "EmergencyContactInfoPhone" => null,
                "EmergencyContactInfoRelationship" => null,
                "Gender" => "Male",
                "LastFormulaNotes" => null,
                "Active" => true,
                "SalesReps" => null,
                "Status" => "Non-Member",
                "Action" => "None",
                "SendAccountEmails" => true,
                "SendAccountTexts" => false,
                "SendPromotionalEmails" => true,
                "SendPromotionalTexts" => false,
                "SendScheduleEmails" => true,
                "SendScheduleTexts" => false,
                "SiteId" => -99787,
            ],

        ]);
    }

    protected function setClientReferralTypes()
    {
        $this->clientReferralTypes = collect([
            [
                0 => "Another Client",
                1 => "Flyer",
                2 => "Internet",
                3 => "Newspaper",
                4 => "Radio",
                5 => "Yellow Pages",
            ],
        ]);
    }

    protected function setPropertySessionTypes()
    {
        $this->sessionTypes = collect([
            [
                "Type" => "Appointment",
                "DefaultTimeLength" => 10,
                "Id" => 5,
                "Name" => "Office Visit",
                "NumDeducted" => 1,
                "ProgramId" => 2,
                "Category" => null,
                "CategoryId" => null,
                "Subcategory" => null,
                "SubcategoryId" => null,
                "siteId" => -99787,
            ],
            [
                "Type" => "Appointment",
                "DefaultTimeLength" => 15,
                "Id" => 6,
                "Name" => "Outpatient Visit New",
                "NumDeducted" => 1,
                "ProgramId" => 2,
                "Category" => "Chiropractor",
                "CategoryId" => 241,
                "Subcategory" => "Adjustment",
                "SubcategoryId" => 242,
                "siteId" => -99787,
            ],
            [
                "Type" => "Appointment",
                "DefaultTimeLength" => 15,
                "Id" => 7,
                "Name" => "add on",
                "NumDeducted" => 1,
                "ProgramId" => 4,
                "Category" => null,
                "CategoryId" => null,
                "Subcategory" => null,
                "SubcategoryId" => null,
                "siteId" => -99787,
            ],
            [
                "Type" => "Class",
                "DefaultTimeLength" => null,
                "Id" => 8,
                "Name" => "Yoga",
                "NumDeducted" => 1,
                "ProgramId" => 24,
                "siteId" => -99787,
            ],
            [
                "Type" => "Class",
                "DefaultTimeLength" => null,
                "Id" => 9,
                "Name" => "Advanced Yoga",
                "NumDeducted" => 1,
                "ProgramId" => 24,
                "siteId" => -99787,
            ],
            [
                "Type" => "Appointment",
                "DefaultTimeLength" => 60,
                "Id" => 10,
                "Name" => "Initial Consultation (60mins)",
                "NumDeducted" => 1,
                "ProgramId" => 4,
                "Category" => "Physical therapy ",
                "CategoryId" => 304,
                "Subcategory" => "General",
                "SubcategoryId" => 312,
                "siteId" => -99787,
            ],
            [
                "Type" => "Appointment",
                "DefaultTimeLength" => 30,
                "Id" => 11,
                "Name" => "Standard Consultation (30mins)",
                "NumDeducted" => 1,
                "ProgramId" => 4,
                "Category" => "Physical therapy ",
                "CategoryId" => 304,
                "Subcategory" => "General",
                "SubcategoryId" => 312,
                "siteId" => -99787,
            ],
            [
                "Type" => "Class",
                "DefaultTimeLength" => 30,
                "Id" => 12,
                "Name" => "Dance",
                "NumDeducted" => 1,
                "ProgramId" => 4,
                "Category" => "Dance",
                "CategoryId" => 304,
                "Subcategory" => "General",
                "SubcategoryId" => 312,
                "siteId" => -99787,
            ],
        ]);
    }

    protected function setAppointments()
    {
        $this->appointments = collect([
            [
                "GenderPreference" => "None",
                "Duration" => 15,
                "ProviderId" => "0",
                "Id" => 70507,
                "Status" => "Arrived",
                "StartDateTime" => '2019-11-14 15:30:00',
                "EndDateTime" => '2019-11-14 15:45:00',
                "Notes" => "running late",
                "StaffRequested" => false,
                "ProgramId" => 2,
                "SessionTypeId" => 6,
                "LocationId" => 2,
                "StaffId" => 2,
                "ClientId" => "new",
                "FirstAppointment" => false,
                "ClientServiceId" => null,
                "Resources" => [],
            ],
            [
                "GenderPreference" => "None",
                "Duration" => 15,
                "ProviderId" => "0",
                "Id" => 70508,
                "Status" => "Completed",
                "StartDateTime" => "2019-11-20T09:30:00",
                "EndDateTime" => "2019-11-20T09:45:00",
                "Notes" => "running late today.98941.",
                "StaffRequested" => false,
                "ProgramId" => 2,
                "SessionTypeId" => 6,
                "LocationId" => 2,
                "StaffId" => 2,
                "ClientId" => "new",
                "FirstAppointment" => false,
                "ClientServiceId" => 10108,
                "Resources" => [],
            ],
            [
                "GenderPreference" => "None",
                "Duration" => 15,
                "ProviderId" => "0",
                "Id" => 70509,
                "Status" => "NoShow",
                "StartDateTime" => "2019-11-20T10:30:00",
                "EndDateTime" => "2019-11-20T10:45:00",
                "Notes" => "",
                "StaffRequested" => false,
                "ProgramId" => 2,
                "SessionTypeId" => 6,
                "LocationId" => 2,
                "StaffId" => 2,
                "ClientId" => "100000001",
                "FirstAppointment" => false,
                "ClientServiceId" => null,
                "Resources" => [],
            ],
            [
                "GenderPreference" => "None",
                "Duration" => 15,
                "ProviderId" => "0",
                "Id" => 70511,
                "Status" => "NoShow",
                "StartDateTime" => "2019-11-21T10:15:00",
                "EndDateTime" => "2019-11-21T10:30:00",
                "Notes" => "running late | book next tues.",
                "StaffRequested" => false,
                "ProgramId" => 2,
                "SessionTypeId" => 6,
                "LocationId" => 2,
                "StaffId" => 2,
                "ClientId" => "new",
                "FirstAppointment" => false,
                "ClientServiceId" => null,
                "Resources" => [],
            ],
            [
                "GenderPreference" => "None",
                "Duration" => 10,
                "ProviderId" => "0",
                "Id" => 70510,
                "Status" => "NoShow",
                "StartDateTime" => "2019-11-20T18:00:00",
                "EndDateTime" => "2019-11-20T18:10:00",
                "Notes" => "",
                "StaffRequested" => false,
                "ProgramId" => 2,
                "SessionTypeId" => 5,
                "LocationId" => 1,
                "StaffId" => 100000003,
                "ClientId" => "hassan_1",
                "FirstAppointment" => true,
                "ClientServiceId" => null,
                "Resources" =>  [
                    [
                        "Id" => 1,
                        "Name" => "Yoga Room",
                    ],
                ],
            ],
        ]);
    }

    protected function setProviderClasses()
    {
        $this->providerClasses = collect([
            [
                "Location" => [
                    "Id" => 1,
                ],
                "Resource" => [
                    "Name" => "Yoga Room",
                ],
                "IsCanceled" => false,
                "Id" => 1445,
                "ClassScheduleId" => 28,
                "StartDateTime" => "2019-11-26T12:00:00",
                "EndDateTime" => "2019-11-26T13:00:00",
                "ClassDescription" => [
                    "Name" => "Yoga",
                    "Notes" => "",
                ],
                "Staff" => [
                    "Id" => 2,
                ],
                "Clients" => collect([]),
            ],
            [
                "Location" => [
                    "Id" => 1,
                ],
                "Resource" => [
                    "Name" => "Yoga Room",
                ],
                "IsCanceled" => false,
                "Id" => 1498,
                "ClassScheduleId" => 29,
                "StartDateTime" => "2019-11-27T12:00:00",
                "EndDateTime" => "2019-11-27T13:00:00",
                "ClassDescription" => [
                    "Name" => "Yoga",
                ],
                "Staff" => [
                    "Id" => 2,
                ],
                "Clients" => collect([]),
            ],
            [
                "Location" => [
                    "Id" => 1,
                ],
                "Resource" => [
                    "Name" => "treatment 1",
                ],
                "IsCanceled" => false,
                "Id" => 1633,
                "ClassScheduleId" => 33,
                "StartDateTime" => "2019-11-26T09:00:00",
                "EndDateTime" => "2019-11-26T10:00:00",
                "ClassDescription" => [
                    "Name" => "Dance Class",
                ],
                "Staff" => [
                    "Id" => 100000003,
                ],
                "Clients" => collect([]),
            ],
            [
                "Location" => [
                    "Id" => 1,
                ],
                "Resource" => [
                    "Name" => "treatment 1",
                ],
                "IsCanceled" => false,
                "Id" => 1643,
                "ClassScheduleId" => 34,
                "StartDateTime" => "2019-11-27T09:00:00",
                "EndDateTime" => "2019-11-27T10:00:00",
                "ClassDescription" => [
                    "Name" => "Dance Class",
                ],
                "Staff" => [
                    "Id" => 100000003,
                ],
                "Clients" => collect([
                    [
                        "client_api_public_id" => "new",
                        "signed_in" => true,
                    ],
                    [
                        "client_api_public_id" => "hassan_1",
                        "signed_in" => true,
                    ],
                ]),
            ],
        ]);
    }

    public function setProviderClassVisit()
    {
        return $this->providerClassVisit = collect([
            [
                "AppointmentId" => 0,
                "AppointmentGenderPreference" => "None",
                "AppointmentStatus" => "None",
                "ClassId" => 1643,
                "ClientId" => "new",
                "StartDateTime" => "2019-11-27T09:00:00",
                "EndDateTime" => "2019-11-27T10:00:00",
                "Id" => 50231,
                "LastModifiedDateTime" => "2019-11-29T20:30:08.6Z",
                "LateCancelled" => false,
                "SiteId" => 0,
                "LocationId" => 1,
                "MakeUp" => false,
                "Name" => "Dance",
                "ServiceId" => 50249,
                "ServiceName" => null,
                "ProductId" => null,
                "SignedIn" => true,
                "StaffId" => 100000003,
                "WebSignup" => false,
                "Action" => "None",
            ],
            [
                "AppointmentId" => 0,
                "AppointmentGenderPreference" => "None",
                "AppointmentStatus" => "None",
                "ClassId" => 1643,
                "ClientId" => "hassan_1",
                "StartDateTime" => "2019-11-27T09:00:00",
                "EndDateTime" => "2019-11-27T10:00:00",
                "Id" => 50230,
                "LastModifiedDateTime" => "2019-11-29T20:30:00.1Z",
                "LateCancelled" => false,
                "SiteId" => 0,
                "LocationId" => 1,
                "MakeUp" => false,
                "Name" => "Dance",
                "ServiceId" => 50248,
                "ServiceName" => null,
                "ProductId" => null,
                "SignedIn" => true,
                "StaffId" => 100000003,
                "WebSignup" => false,
                "Action" => "None",
            ],
        ]);
    }
}
